name: Playwright Tests (Assignment 2 Only)

on:
  push:
    branches:
      - main

jobs:
  test-assignment2:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Assignment2   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run regression

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: assignment2/playwright-report/